spring:

  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 1800000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 3000
      connection-test-query: SELECT 1


  redis:
    host: 192.168.25.128
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-wait: 10000ms
        max-active: 8
        max-idle: 200
        min-idle: 5

  rabbitmq:
    host: 192.168.25.128
    username: guest
    password: guest
    virtual-host: /
    port: 5672
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3
        max-interval: 10000ms
        multiplier: 1


  web:
    resources:
      add-mappings: true
      cache:
        cachecontrol:
          max-age: 3600
      chain:
        cache: true
        enabled: true
        compressed: true

      static-locations: classpath:/static/



mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.linlin.seckill.pojo


logging:
  level:
    com.linlin.seckill.mapper: debug
